services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports:
      - 5432:5432
    secrets:
      - db_password
      - db_user
      - db_name
    networks:
      - server

  server:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./env/config:/go/src/server/config
    ports:
      - 3000:3000
    networks:
      - server

networks:
  server:
    driver: bridge

secrets:
  db_password:
    file: ./env/secrets/db_password
  db_user:
    file: ./env/secrets/db_user
  db_name:
    file: ./env/secrets/db_name